<?php

namespace Src\DesignPatterns\ChainOfResponsibility\RegistrationService\checkers;

use App\Models\User;
use Src\DesignPatterns\ChainOfResponsibility\RegistrationService\Checker;
use Src\DesignPatterns\ChainOfResponsibility\RegistrationService\RegistrationRequest;

class EmailChecker extends Checker
{
    public function check(RegistrationRequest $request): bool
    {
        if ($this->emailCheck($request->getEmail())) {
            return false;
        }
        return parent::check($request); // TODO: Change the autogenerated stub
    }

    private function emailCheck(string $email)
    {
        return User::whereEmail($email)->exists();
    }

}
